### ISSUE TITLE
Add theming

### ISSUE THREAD

**Issue by Lamparter** [0x5bfa/FluentHub#158]
### Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### Description

Add options to select various different themes in a similar way to @files-community.

**Comment by onein528** [comment]
yes. I have Theme/Default dir, but I have added that resources previously, occurred unknown xaml exception.

**Comment by DeveloperWOW64** [comment]
> yes. I have Theme/Default dir, but I have added that resources previously, occurred unknown xaml exception.

Yeah I saw that - maybe want to ask @yaichenbaum how it works in Files

**Comment by onein528** [comment]
I see.
