### ISSUE TITLE
Feature: Add push-notification functionality

### ISSUE THREAD

**Issue by 0x5bfa** [0x5bfa/FluentHub#166]
Ghostly might help us.

**Comment by onein528** [comment]
https://github.com/patriksvensson/ghostly

**Comment by ioapiset** [comment]
Good

**Comment by onein528** [comment]
How about setting up a task to get notifications every 15 seconds?

**Comment by onein528** [comment]
Yep. I am not familiar with background tasks and toast notifications. so it will take long time to implement this(have to learn about that).

**Comment by DeveloperWOW64** [comment]
> have to learn about that.

https://apps.microsoft.com/store/detail/notifications-visualizer/9NBLGGH5XSL1

**Comment by onein528** [comment]
15 seconds is too long?

**Comment by onein528** [comment]
and I dont know if this is best way to get.

**Comment by DeveloperWOW64** [comment]
> and I dont know if this is best way to get.

WDYM?

**Comment by onein528** [comment]
Is it correct to get notifications at background time intervals and toast new items.

**Comment by onein528** [comment]
Unigram might help us

**Comment by DeveloperWOW64** [comment]
> Unigram might help us

How? It's just a telegram client.

**Comment by onein528** [comment]
yea. but unigram created with UWP and uses toat messaging.

**Comment by DeveloperWOW64** [comment]
> Ghostly might help us.

If we used the GQL the user would need ghostly installed i think

**Comment by DeveloperWOW64** [comment]
Hmmmmmmmmm

**Comment by onein528** [comment]
WASDK might enable us to implemet push notification feature. If we set up our FluentHub website, could we also set up web hooking?

**Comment by DeveloperWOW64** [comment]
> WASDK might enable us to implemet push notification feature. If we set up our FluentHub website, could we also set up web hooking?

Perhaps. I'm not a push-notification expert, but it should be possible. Feel free to use https://codrex.dev / related subdomains for push notifications, i don't mind. @onein528

**Comment by onein528** [comment]
I appreciate for it.

**Comment by DeveloperWOW64** [comment]
👀
![image](https://user-images.githubusercontent.com/71598437/188080175-2c0750c9-cfaa-47a3-bda9-3d890bb12f80.png)

**Comment by onein528** [comment]
This lib is for toast notification
