### ISSUE TITLE
Replace EmojiIcons with web URLs

### ISSUE THREAD

**Issue by Lamparter** [0x5bfa/FluentHub#247]
### 🛤️ Feature

Replaces EmojiIcons with web URLs.

### 📄 Description

The app already depends on the internet to make queries so why not rely on the internet to get the icons anyway?

**Comment by onein528** [comment]
Should not be more depend on web. If there's no internet, App just seems to be dead screen.

**Comment by onein528** [comment]
What? Please comment.

**Comment by DeveloperWOW64** [comment]
> Which? Please comment.

What on earth are you talking about? Ahh you mean #251?

**Comment by onein528** [comment]
> Your problem was solved? (if so, please close this)

This.

**Comment by DeveloperWOW64** [comment]
> This. If you won't close this and have any thoughts, please let me know....

@onein528 I would like to develop on this issue.

**Comment by onein528** [comment]
I'd like to know more about this. Where exactly are you talking about? What is 'EmojiIcons'.

**Comment by DeveloperWOW64** [comment]
> I'd like to know more about this. Where exactly are you talking about? What is 'EmojiIcons'.

[Icons](https://github.com/FluentHub/FluentHub/tree/main/src/FluentHub.Uwp/Assets/Icons)
I previously called them emojiicons because *you* called them that lol

**Comment by onein528** [comment]
Ah, Ok, understand. Even when you don't have an Internet connection, the app needs to run at least correctly.

**Comment by onein528** [comment]
Outdated
