### ISSUE TITLE
Feature: Add page content caching service

### ISSUE THREAD

**Issue by Lamparter** [0x5bfa/FluentHub#248]
### ⏱️ Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### 📄 Description

Implement cache so if the user has no internet, FluentHub doesn't break immediately.

### 🗃️ Alternative solutions

None.

### 📸 Assets

None

**Comment by onein528** [comment]
I'm not sure we should use cache. Cache is for not getting extra data. But shouldn't do like that due to it's characteristics of Octokit.GrapgQL.NET

**Comment by arihant2math** [comment]
Also switching between pages that include api calls takes a bit.

**Comment by onein528** [comment]
Yes. I'm thinking of displaying the control first and displaying it as soon as an error occurs.
