### ISSUE TITLE
v1.0 shipping progress

### ISSUE THREAD

**Issue by Lamparter** [0x5bfa/FluentHub#253]
# Post v1.0

## WASDK Migration

- [x] https://github.com/FluentHub/FluentHub/labels/breaking%20change #316 

## User pages

- Implement user package page
- Implement user projects page
- Implement editing user profile dialog
- Implement editing basic user information
- Add user's popular repos and make repos pinnable
- Improve user experience of user contribution graph
 feature request This issue is a feature request.Implement user contribution details page #269
 feature request This issue is a feature request.Implement adding/removing a repository as star #271
 feature request This issue is a feature request.suspended/abandoned/notplanned This issue/PR has been suspended or abandoned, and will not continue work until it is resolved.Implement user star list
 feature request This issue is a feature request.Implement status (of users) #272
➡️ approved This PR has been approved by an FH member.General Updates 17 #259
 feature request This issue is a feature request.Implement changing status context #273
Repository pages
 bug This issue is related to a bug in the app.Fix the number of branches and tags to be displayed  #274
 feature request This issue is a feature request.Implement the ability to create a branch #275
 feature request This issue is a feature request.Implement a function that allows you to navigate from repo page to VSCode #276
feature request This issue is a feature request.Feature: Add edit code with VSCode button to repository code page #188
 feature request This issue is a feature request.Develop repository release page #277
➡️ approved This PR has been approved by an FH member.General Updates 17 #259
 feature request This issue is a feature request.Implement the ability to edit repository details #278
 feature request This issue is a feature request.Update repository Discussion page #279
 feature request This issue is a feature request.Update repository Project page #280
 feature request This issue is a feature request.Implement repository Actions page #281
 feature request This issue is a feature request.Implement repository pulse page #282
 feature request This issue is a feature request.Implement repository contributors page #283
 feature request This issue is a feature request.Implememt repository traffic page #284
 feature request This issue is a feature request.Implement repository commits page #285
 feature request This issue is a feature request.Implement repository code change frequency page #286
 feature request This issue is a feature request.Fix repository settings page #287
➡️ feature request This issue is a feature request.Implement repository settings page #217
Organization pages
 feature request This issue is a feature request.Implement the ability to display organization README from .github or .github-private #288
 feature request This issue is a feature request.Implement organization Discussions page #289
 feature request This issue is a feature request.Implement organization Projects page #290
 feature request This issue is a feature request.Implement organization Packages page #291
 feature request This issue is a feature request.Implement organization settings page #292
Others
 feature request This issue is a feature request.Feature: Support full localization resources #317
➡️ approved This PR has been approved by an FH member.Localize/ise FluentHub #244
 feature request This issue is a feature request.Implement filtering feature generally #270
 bug This issue is related to a bug in the app.Feature: Update app settings page #293
 feature request This issue is a feature request.Update app settings page content #294
 bug This issue is related to a bug in the app.The notifications page only shows 3 notifications #296
 bug This issue is related to a bug in the app.Bug: Opening repos and issues sometimes causes the app to crash #260
 bug This issue is related to a bug in the app.Bug: Opening Issues sometimes crashes the app #297
 bug This issue is related to a bug in the app.Bug: Opening the commit history sometimes crashes the app #298
 bug This issue is related to a bug in the app.Bug: Opening a pull request sometimes crashes the app #299
 feature request This issue is a feature request.Feature: Add push-notification functionality #166
 bug This issue is related to a bug in the app.App icon is not displayed in the title grid and intro page #229
➡️ approved This PR has been approved by an FH member.General Updates 17 #259
 feature request This issue is a feature request.Feature: Add page content caching service #248
 bug This issue is related to a bug in the app.Bug: Home and About page does not load after logged in #305
 feature request This issue is a feature request.Feature: Add theming functionality #328
➡️ approved This PR has been approved by an FH member.Add theming #158
➡️ approved This PR has been approved by an FH member.Add Theming #163

**Comment by DeveloperWOW64** [comment]
I saw documentation about a CLI called the .NET Update Assistant that might be able to automate the process. 👀

**Comment by DeveloperWOW64** [comment]
@onein528 Should we start on this now?

**Comment by onein528** [comment]
Yep. Really exciting.

**Comment by onein528** [comment]
@DeveloperWOW64 How about?

**Comment by DeveloperWOW64** [comment]
> @DeveloperWOW64 How about?

YES. DEFINITELY.

**Comment by arihant2math** [comment]
I'd like to see #295 and #296 resolved before 1.0 because they are some bugs that I can find that are 1 click away from the homepage.

**Comment by arihant2math** [comment]
#300 is something to keep in mind while implementing #281

**Comment by arihant2math** [comment]
Also WASDK doesn't have some features, I'm not sure if the unsupported features are used here.

**Comment by DeveloperWOW64** [comment]
> Also WASDK doesn't have some features, I'm not sure if the unsupported features are used here.

Do you know what they are? @arihant2math

**Comment by arihant2math** [comment]
I can't come up with a comprehensive list but:

- Input validation
- ~~Media Player Element~~ 1.2 preview
- ~~Multiple top-level windows on separate threads~~ experimental
There probably are others but these are the major ones I can think of.

**Comment by onein528** [comment]
Title bar customizing is supported? @arihant2math

**Comment by onein528** [comment]
We need to verify if WinUI 3.0(WASDK) will be fit to FluentHub. Until come true, should not consider about it.

**Comment by DeveloperWOW64** [comment]
> Title bar customizing is supported? @arihant2math

Yes. @onein528

**Comment by onein528** [comment]
Do you think it's better to complete the v1 milestone first or the WASDK milestone?

**Comment by DeveloperWOW64** [comment]
> Do you think it's better to complete the v1 milestone first or the WASDK milestone?

Hmmm. I don't know.

**Comment by onein528** [comment]
Ok. I decided to proceed both.

**Comment by onein528** [comment]
Please simplify TODO check boxes... Not need to be such detailed.

**Comment by DeveloperWOW64** [comment]
> Please simplify TODO check boxes... Not need to be such detailed. (But thank you!)

(but I worked so hard on them!) Ok.
*logging on to github from my school so I can only talk in a polite English manner (school rules for computers), but at least I can use GitHub*

**Comment by Lamparter** [comment]
Closed by #488
