### ISSUE TITLE
Files have weird filenames even though they are just mp3s

### ISSUE THREAD

**Issue by Magess** [0x5bfa/FluentHub#452]
### Before you start

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### What version of Windows is this issue present?

Windows 10

### What version/architecture of FluentHub are you on?

Version 2023.1019.113.0 

### Description

I opened the file folder for my downloaded podcasts, and they all have bizarre filenames and cannot be played as mp3s without being renamed.
![fluentcast](https://github.com/FluentHub/FluentHub/assets/8743308/0572bcc8-5ea5-4f63-92ba-212d5894cf71)

A sample filename: Chapter 4 What's the Frequency Dearest.mp3token-time=1707004800&token-hash=PInjfqd9wCbFsNr-p3EuhqcJ1--Ato_e-CaDFGzUlog%3D

The RSS feed is for a patreon subscriber feed, so it does have an auth key in the feed link. 

https://www.patreon.com/rss/midnightburger?auth=Mn43oLwPeVyvkxJFVJCBOAOA56hOka9R

### Steps To Reproduce

1. Go to Subscriptions
2. Go to Add podcast
3. Paste https://www.patreon.com/rss/midnightburger?auth=Mn43oLwPeVyvkxJFVJCBOAOA56hOka9R
4. Go to Midnight Burger podcast
5. Go to burger menu and select to Download > All Episodes.

### Expected behavior

The files should have only the .mp3 file extension. When the files are renamed, they play fine. 

### Stack Trace

<details><summary>Stack trace details</summary><div>

```
paste here
```

</div></details>

**Comment by 0x5bfa** [comment]
You may have posted the issue to the wrong repository.
