### ISSUE TITLE
Almost everything is unclickable

### ISSUE THREAD

**Issue by Andrew-Sor** [0x5bfa/FluentHub#467]
### Before you start

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### What version of Windows is this issue present?

Windows 11

### What version/architecture of FluentHub are you on?

0.8.60.0 | X64 | RELEASE

### Description

https://github.com/0x5bfa/FluentHub/assets/133566800/7afae3cc-9ea8-4f19-a40b-d3c18f3e0b23

### Expected behavior

Performance of the elements shown in the video.

### Stack Trace

<details><summary>Stack trace details</summary><div>

```
paste here
```

</div></details>

### Assets

https://github.com/0x5bfa/FluentHub/assets/133566800/d50f9ecb-369c-4b51-8d17-2af30929c632

**Comment by 0x5bfa** [comment]
Thanks for the feedback, those are not implemented yet. But sidebar’s issue has been fixed but not published in the store.

**Comment by Andrew-Sor** [comment]
It's now clear. Thanks

**Comment by pdimu** [comment]
#459 an issue that goes more in-depth through this issue
