### ISSUE TITLE
GitHub: Add SECURITY.md

### ISSUE THREAD

**Issue by Lamparter** [0x5bfa/FluentHub#500]
We should add a security.md file to demonstrate how to report a security vulnerability.

**Comment by 0x5bfa** [comment]
How the format should be?

**Comment by Lamparter** [comment]
> How the format should be?

@0x5bfa only you can do this. https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository#adding-a-security-policy-to-your-repository

**Comment by Lamparter** [comment]
I can change it once you add it

**Comment by 0x5bfa** [comment]
Done
