### ISSUE TITLE
Bug: Error loading home page

### ISSUE THREAD

**Issue by Richard5A** [0x5bfa/FluentHub#520]
### 🪟 What version of Windows is this issue present?

🪟 Windows 11

### 🔢 What version of FluentHub are you on?

0.9.0.0 | X64 | RELEASE

### 📄 Description

When opening the app, I shortly see some results on the left pane. Then the app shows the error screen. The only page with this problem is the dashboard.

### 🪜 Steps To Reproduce

idk if you can reproduce it, but when I'm logged in and start the app I get the error.

### 🤔 Expected behavior

No error

### ⚒️ Did you find any workaround?

Nope.

### 📑 Stack Trace

<details><summary>Stack trace details</summary><div>

```
   at FluentHub.Octokit.Wrappers.ActivityWrapper.Wrap(IReadOnlyList`1 response)
   at FluentHub.Octokit.Queries.Users.ActivityQueries.GetAllAsync(String login)
   at FluentHub.App.ViewModels.Viewers.DashBoardViewModel.LoadHomeContentsAsync()
   at FluentHub.App.ViewModels.Viewers.DashBoardViewModel.LoadUserHomePageAsync()
```

</div></details>

**Comment by Richard5A** [comment]
Duplicate

**Comment by Lamparter** [comment]
Thanks for noticing this was a duplicate. You can click **subscribe** in the sidebar on the issue #517 to subscribe to notifications about updates and a potential fix.
