### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by beecho01** [0x5bfa/FluentHub#521]
### 🪟 What version of Windows is this issue present?

🪟 Windows 11

### 🔢 What version of FluentHub are you on?

0.9.0.0 | X64 | RELEASE

### 📄 Description

When loading the application into the initial dashboard, an error is thrown after a few seconds.

### 🪜 Steps To Reproduce

1. Load application
2. Wait whilst dashboard populates
3. Error page shown

### 🤔 Expected behavior

The dashboard should load and sidebar populated without issue.

### ⚒️ Did you find any workaround?

No

### 📑 Stack Trace

<details><summary>Stack trace details</summary><div>

```
at FluentHub.Octokit.Wrappers.ActivityWrapper.Wrap(IReadOnlyList`1 response)
at FluentHub.Octokit.Queries.Users.ActivityQueries.GetAllAsync(String login)
at FluentHub.App.ViewModels.Viewers.DashBoardViewModel.LoadHomeContentsAsync()
at FluentHub.App.ViewModels.Viewers.DashBoardViewModel.LoadUserHomePageAsync()
```

</div></details>

### 📸 Assets

<img width="1431" alt="FluentHub_xa57W0fCGY" src="https://github.com/user-attachments/assets/be8e84fe-009e-491e-96fa-c6d2376ff6ff">

**Comment by Lamparter** [comment]
Hello @beecho01! We're tracking this issue in #517. You can click **subscribe** in the sidebar on the issue I just mentioned to subscribe to notifications about updates and a potential fix.
